name: r_unfair
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - pip:
      - datasets
      - lightning
      - mlflow
      - onnx
      - peft
      - polars
      - sentencepiece
      - torch
      - torchmetrics
      - transformers
